import { defineField, defineType } from "sanity";

export default defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "general", title: "General Settings" },
    { name: "hero", title: "Hero Section" },
    { name: "about", title: "About Coach Section" },
    { name: "personal", title: "Personal Training Section" },
    { name: "online", title: "Online Coaching Section" },
    { name: "contact", title: "Contact Section" },
    { name: "form", title: "Application Form" },
  ],
  fields: [
    // --- General Settings ---
    defineField({
      name: "title",
      title: "Settings Identifier",
      type: "string",
      initialValue: "Global Site Configurations",
      readOnly: true,
      group: "general",
    }),
    defineField({
      name: "whatsAppNumber",
      title: "WhatsApp Phone Number",
      type: "string",
      description: "WhatsApp phone number without spaces or + (e.g., '64220749673')",
      group: "general",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact Email Address",
      type: "string",
      description: "Target email for customer inquiries (e.g., 'kalerbodyfocus@gmail.com')",
      group: "general",
    }),
    defineField({
      name: "locationText",
      title: "Physical Location Text",
      type: "string",
      description: "Physical location displayed on the website (e.g., 'Christchurch, New Zealand')",
      group: "general",
    }),
    defineField({
      name: "googleBusinessUrl",
      title: "Google Business Review Link",
      type: "string",
      description: "Direct URL to your Google Reviews or Google Business profile",
      group: "general",
    }),
    defineField({
      name: "googleReviewsWidgetId",
      title: "Google Reviews Widget ID (Trustindex)",
      type: "string",
      description: "The Trustindex widget ID (e.g., '3af0aa774b6290282176083149d') from the loader.js?ID script",
      group: "general",
    }),
    defineField({
      name: "googleReviewsWidgetUrl",
      title: "Google Reviews Widget Iframe URL (Trustindex)",
      type: "string",
      description: "Fallback iframe URL from Trustindex (e.g., 'https://cdn.trustindex.io/amp.php?3af0aa774b6290282176083149d')",
      group: "general",
    }),
    defineField({
      name: "trustBarItems",
      title: "Marquee Bullet Points",
      type: "array",
      of: [{ type: "string" }],
      description: "Text bullets moving across the screen (e.g., 'Evidence-Based Training', etc.)",
      group: "general",
    }),

    // --- Hero Section ---
    defineField({
      name: "heroImage",
      title: "Hero Background Image",
      type: "image",
      description: "Background photo for the Hero section at the top of the homepage",
      options: {
        hotspot: true,
      },
      group: "hero",
    }),
    defineField({
      name: "heroTitleLine1",
      title: "Headline Line 1",
      type: "string",
      description: "e.g., 'Train With'",
      group: "hero",
    }),
    defineField({
      name: "heroTitleLine2",
      title: "Headline Line 2 (Italic & Gold)",
      type: "string",
      description: "e.g., 'Focus.'",
      group: "hero",
    }),
    defineField({
      name: "heroTitleLine3",
      title: "Headline Line 3",
      type: "string",
      description: "e.g., 'Not Frustration.'",
      group: "hero",
    }),
    defineField({
      name: "heroDescription",
      title: "Headline Subtitle / Paragraph",
      type: "text",
      description: "Intro text below the main headline",
      group: "hero",
    }),
    defineField({
      name: "heroPrimaryCta",
      title: "Hero Button: In-Person CTA",
      type: "string",
      description: "Text on the main button (e.g., 'Book In-Person Consultation')",
      group: "hero",
    }),
    defineField({
      name: "heroSecondaryCta",
      title: "Hero Button: Online CTA",
      type: "string",
      description: "Text on the secondary button (e.g., 'Start Online Coaching')",
      group: "hero",
    }),
    defineField({
      name: "freeConsultationAlert",
      title: "Free Consultation Promo Text",
      type: "string",
      description: "Header alert text (e.g., 'Free 60-Minute In-Person Consultation in Christchurch')",
      group: "hero",
    }),
    defineField({
      name: "heroStat1Value",
      title: "Stat 1 Number",
      type: "number",
      description: "e.g., 500",
      group: "hero",
    }),
    defineField({
      name: "heroStat1Suffix",
      title: "Stat 1 Suffix",
      type: "string",
      description: "e.g., '+' or '%'",
      group: "hero",
    }),
    defineField({
      name: "heroStat1Label",
      title: "Stat 1 Label",
      type: "string",
      description: "e.g., 'Sessions Delivered'",
      group: "hero",
    }),
    defineField({
      name: "heroStat2Value",
      title: "Stat 2 Number",
      type: "number",
      description: "e.g., 98",
      group: "hero",
    }),
    defineField({
      name: "heroStat2Suffix",
      title: "Stat 2 Suffix",
      type: "string",
      description: "e.g., '+' or '%'",
      group: "hero",
    }),
    defineField({
      name: "heroStat2Label",
      title: "Stat 2 Label",
      type: "string",
      description: "e.g., 'Client Satisfaction'",
      group: "hero",
    }),
    defineField({
      name: "heroStat3Value",
      title: "Stat 3 Number",
      type: "number",
      description: "e.g., 7",
      group: "hero",
    }),
    defineField({
      name: "heroStat3Suffix",
      title: "Stat 3 Suffix",
      type: "string",
      description: "e.g., '+' or '%'",
      group: "hero",
    }),
    defineField({
      name: "heroStat3Label",
      title: "Stat 3 Label",
      type: "string",
      description: "e.g., 'Years Coaching'",
      group: "hero",
    }),

    // --- About Section ---
    defineField({
      name: "aboutTitle",
      title: "About Title",
      type: "string",
      description: "e.g., 'Ranjit Singh.'",
      group: "about",
    }),
    defineField({
      name: "aboutSubtitle",
      title: "About Subtitle",
      type: "string",
      description: "e.g., 'Built to Coach.'",
      group: "about",
    }),
    defineField({
      name: "aboutParagraph1",
      title: "About Paragraph 1",
      type: "text",
      group: "about",
    }),
    defineField({
      name: "aboutParagraph2",
      title: "About Paragraph 2",
      type: "text",
      group: "about",
    }),
    defineField({
      name: "aboutTags",
      title: "About Badges",
      type: "array",
      of: [{ type: "string" }],
      description: "e.g., 'No shortcuts', 'No crash diets', 'No generic programs'",
      group: "about",
    }),
    defineField({
      name: "aboutStatValue",
      title: "About Highlight Stat Value",
      type: "string",
      description: "e.g., '7+'",
      group: "about",
    }),
    defineField({
      name: "aboutStatLabel",
      title: "About Highlight Stat Label",
      type: "string",
      description: "e.g., 'Years transforming busy professionals & parents'",
      group: "about",
    }),
    defineField({
      name: "aboutImage",
      title: "About Photo / Avatar",
      type: "image",
      description: "Portrait photo of the coach",
      options: {
        hotspot: true,
      },
      group: "about",
    }),

    // --- Personal Training Section ---
    defineField({
      name: "personalImage",
      title: "Personal Training Background Image",
      type: "image",
      description: "Background photo for the Personal Training section",
      options: {
        hotspot: true,
      },
      group: "personal",
    }),
    defineField({
      name: "personalTitle",
      title: "Personal Training Title",
      type: "string",
      description: "e.g., 'Personal Coaching.'",
      group: "personal",
    }),
    defineField({
      name: "personalSubtitle",
      title: "Personal Training Subtitle",
      type: "string",
      description: "e.g., 'Personalized Results.'",
      group: "personal",
    }),
    defineField({
      name: "personalDescription",
      title: "Personal Training Description",
      type: "text",
      group: "personal",
    }),
    defineField({
      name: "personalIncludes",
      title: "Personal Training: What's Included Bullets",
      type: "array",
      of: [{ type: "string" }],
      group: "personal",
    }),
    defineField({
      name: "personalIdealFor",
      title: "Personal Training: Ideal For Bullets",
      type: "array",
      of: [{ type: "string" }],
      group: "personal",
    }),

    // --- Online Section ---
    defineField({
      name: "onlineTitle",
      title: "Online Coaching Title",
      type: "string",
      description: "e.g., 'Professional Coaching'",
      group: "online",
    }),
    defineField({
      name: "onlineSubtitle",
      title: "Online Coaching Subtitle",
      type: "string",
      description: "e.g., 'Wherever You Are.'",
      group: "online",
    }),
    defineField({
      name: "onlineDescription",
      title: "Online Coaching Description",
      type: "text",
      group: "online",
    }),
    defineField({
      name: "onlineFeatures",
      title: "Online Coaching Features List",
      type: "array",
      of: [{ type: "string" }],
      description: "Features list (e.g. 'Customized training plans', etc.)",
      group: "online",
    }),
    defineField({
      name: "onlineImage",
      title: "Online Section Image",
      type: "image",
      options: {
        hotspot: true,
      },
      group: "online",
    }),

    // --- Contact Section ---
    defineField({
      name: "contactTitle",
      title: "Contact Section Title",
      type: "string",
      description: "e.g., 'Let's get started.'",
      group: "contact",
    }),
    defineField({
      name: "contactDescription",
      title: "Contact Section Description",
      type: "text",
      description: "Instruction paragraph above email and social handles",
      group: "contact",
    }),

    // --- Application Form Settings ---
    defineField({
      name: "formShowAge",
      title: "Form: Show Age Field",
      type: "boolean",
      description: "Toggle whether to ask for Age in the inquiry form",
      initialValue: true,
      group: "form",
    }),
    defineField({
      name: "formShowBodyStats",
      title: "Form: Show Weight & Height",
      type: "boolean",
      description: "Toggle whether to ask for Weight & Height in the inquiry form",
      initialValue: true,
      group: "form",
    }),
    defineField({
      name: "formShowWhatsApp",
      title: "Form: Show WhatsApp Field",
      type: "boolean",
      description: "Toggle whether to ask for WhatsApp number in the inquiry form",
      initialValue: true,
      group: "form",
    }),

    // --- Form Question Labels (Challenges Step) ---
    defineField({
      name: "formMotivationQuestion",
      title: "Form: 'Motivation' Question Label",
      type: "string",
      description: "The question shown for motivation field in Step 4",
      initialValue: "Why Did You Decide to Start Your Fitness Journey Now?",
      group: "form",
    }),
    defineField({
      name: "formOutcomeQuestion",
      title: "Form: 'Expected Outcome' Question Label",
      type: "string",
      description: "The question shown for outcome field in Step 4",
      initialValue: "What Are Your Expected Outcomes from This Coaching Program?",
      group: "form",
    }),
    defineField({
      name: "formStruggleQuestion",
      title: "Form: 'Biggest Struggle' Question Label",
      type: "string",
      description: "The question shown for biggest struggle field in Step 4",
      initialValue: "What Is Your Biggest Fitness Struggle?",
      group: "form",
    }),
    defineField({
      name: "formPreviousQuestion",
      title: "Form: 'Previous Attempts' Question Label",
      type: "string",
      description: "The question shown for previous attempts field in Step 4",
      initialValue: "Why Have Your Previous Attempts Failed?",
      group: "form",
    }),

    // --- Form Question Labels (Goals Step) ---
    defineField({
      name: "formGoalQuestion",
      title: "Form: 'Primary Goal' Question Label",
      type: "string",
      description: "The question shown for primary goal in Step 2",
      initialValue: "What Is Your Primary Goal?",
      group: "form",
    }),

    // --- Form Question Labels (Lead Source Step) ---
    defineField({
      name: "formSourceQuestion",
      title: "Form: 'How Did You Hear' Question Label",
      type: "string",
      description: "The question shown for how they heard about you in Step 5",
      initialValue: "How Did You Hear About Us?",
      group: "form",
    }),
  ],
});
